version: "3.8"

services:
  app:
    build: .
    env_file: 
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start